---
name: Algorithm-SkipList
version: 2.00_02
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
abstract: Perl implementation of skip lists
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 0
  Tree::Node: 0.07
  base: 0
  perl: v5.6.0
  self: 0.3
recommends:
  IO::Scalar: 0
  Test::Memory::Cycle: 0
  Test::Portability::Files: 0
configure_requires:
  Module::Build: 0.35
provides:
  Algorithm::SkipList:
    file: lib/Algorithm/SkipList.pm
    version: 2.00_02
  Algorithm::SkipList::Header:
    file: lib/Algorithm/SkipList/Header.pm
    version: 2.00_02
  Algorithm::SkipList::Node:
    file: lib/Algorithm/SkipList/Node.pm
    version: 2.00_02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
